name: Update Cargo sources

on: [pull_request]

jobs:
  update-sources:
    runs-on: ubuntu-latest
    #if: github.actor == 'flathubbot'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Retrieve tag from manifest
        id: manifestTagVersion
        run: |
          echo "TAG_VERSION=$(jq -r '.modules[0].sources[0].tag' io.github.simoonas.marca.json)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          path: marca
          repository: simoonas/Marca
          ref: ${{ steps.manifestTagVersion.outputs.TAG_VERSION }}

      - name: Update cargo-sources.json
        run: |
          sudo apt-get update -y && sudo apt-get install -y python3-aiohttp python3-tomlkit
          curl -O https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/cargo/flatpak-cargo-generator.py
          python3 flatpak-cargo-generator.py marca/Cargo.lock -o cargo-sources.json 
          rm -rf marca
          [[ ! $(git status --porcelain) ]] && exit 0
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add cargo-sources.json
          git commit -m 'Update cargo-sources.json'
          git push
