name: Update manifest and cargo-sources
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Fix directory permissions
        run: sudo chown -R $USER:$USER .
        
      # Check upstream and update manifest if a new tag exists
      - name: Run Checker
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --commit-only --never-fork io.github.simoonas.marca.json

      # If update happened, checker leaves behind the upstream in clone/
      - name: Regenerate Cargo Sources
        run: |
          if [ -d "clone/io.github.simoonas.marca" ]; then
            curl -O https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/cargo/flatpak-cargo-generator.py
            python3 flatpak-cargo-generator.py clone/io.github.simoonas.marca/Cargo.lock -o cargo-sources.json
          fi
      # Detect modified files, commit them, open PR
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: master
          signoff: false
          branch: pr/update-manifest
          commit-message: "Update version and cargo-sources.json"
          title: "Update upstream release"
          delete-branch: true
